allin<-list(page10 = list(number_of_dataset = 2,
                          plot_type = c('bar','bar'),
                          dataset_names = c('doc_cnt_qtr',
                                            'doc_cnt_qtr'),
                          dataset_1 = list(x = 'Quarter',
                                           y = 'doc_cnt',
                                           title_plot = "Total Physicians' Count by Quarter"),
                          dataset_2 = list(x = 'Quarter',
                                           y = 'count_change',
                                           title_plot = 'Counts Change of Physicians by Quarter'),
                          layout = 'two charts horizantal',
                          title_char = "每季度受访医生数目递增情况及总体分析人数"),
            
            page11 = list(number_of_dataset = 3,
                          plot_type = c('pie','pie','pie'),
                          dataset_names = c("tmp_doc_region_dist_qtr",
                                            "tmp_doc_level_dist_qtr",
                                            "tmp_doc_department_dist_qtr"),
                          dataset_1 = list(x = "region",
                                           y = "doc_cnt",
                                           title_plot = "Region Distribution of Physicians"),
                          dataset_2 = list(x = "doctor.tier",
                                           y = "doc_cnt",
                                           title_plot = "Level Distribution of Physicians"),
                          dataset_3 = list(x = "department",
                                           y = "doc_cnt",
                                           title_plot = "Department Distribution of Physicians"),
                          layout = 'four charts',
                          title_char = "各季度受访医生的总体分布情况"),

            page12 = list(number_of_dataset = 2,
                          plot_type = c('line','stacked bar'),
                          dataset_names = c("tmp_doc_perception_score_tier_qtr",
                                            "tmp_doc_perception_score_tier_qtr"),
                          dataset_1 = list(x = "Quarter",
                                           y = "doc_cnt.x",
                                           title_plot = (paste("Tracking of ", input$level,
                                                               " Physicians Scores by Quarter")),
                                           linetype = "hcp.major",
                                           color = "hcp.major",
                                           x_axis = "Quarter",
                                           y_axis="Physicians Count"),
                          dataset_2 = list(x = "Quarter",
                                           y = "doc_cnt_pct",
                                           title_plot = (paste("Distribution of ", input$level,
                                                               " Physicians Scores by Quarter")),
                                           x_axis = "Quarter",
                                           y_axis = "Percentage"),
                          layout = 'two charts horizantal',
                          title_char = "每季度各个观念级别的受访医生数目及比例变化情况"),

            page13 = list(number_of_dataset = 3,
                          plot_type = c("stacked bar",
                                        "stacked bar",
                                        "stacked bar"),
                          dataset_names = c("tmp_doc_perception_score_region_qtr",
                                            "tmp1_doc_perception_score_tier_qtr",
                                            "tmp_doc_perception_score_department_qtr"),
                          dataset_1 = list(x = "region",
                                           y = "doc_cnt_pct",
                                           title_plot = (paste("Distribution of Physicians Scores by Region in ",
                                                               input$year, input$quarter, sep = "")),
                                           color = "hcp.major",
                                           x_axis = "Region",
                                           y_axis = "Percentage"),
                          dataset_2 = list(x = "doctor.tier",
                                           y = "doc_cnt_pct",
                                           title_plot = (paste("Distribution of Physicians Scores by Doctor Level in ",
                                                               input$year, input$quarter, sep = "")),
                                           color = "hcp.major",
                                           x_axis = "Doctor Level",
                                           y_axis = "Percentage"),
                          dataset_3 = list(x = "department",
                                           y = "doc_cnt_pct",
                                           title_plot = (paste("Distribution of Physicians Scores by Department in ",
                                                               input$year, input$quarter, sep = "")),
                                           color = "hcp.major",
                                           x_axis = "Department",
                                           y_axis = "Percentage"),
                          layout = "four charts",
                          title_char = "各季度不同观念级别医生的分布情况"),

            page14 = list(number_of_dataset = 2,
                          plot_type = c("line","line"),
                          dataset_names = c("tmp_eda_dat_15_q",
                                            "tmp_eda_dat_16_q"),
                          dataset_1 = list(x = "hcp.major",
                                           y = "doc_cnt_pct",
                                           title_plot = (paste("Sporanox Advantages Accepted by Physician with Different Scores in",
                                                               input$year, input$quarter, sep = "")),
                                           linetype = "answers",
                                           color = "answers",
                                           x_axis = "HCP Major",
                                           y_axis = "Percentage"),
                          dataset_2 = list(x = "hcp.major",
                                           y ="doc_cnt_pct",
                                           title_plot = (paste("Sporanox Promotions Accepted by Physician with Different Scores ",
                                                               input$year, input$quarter, sep = "")),
                                           linetype = "answers",
                                           color = "answers",
                                           x_axis = "HCP Major",
                                           y_axis = "Percentage"),
                          layout = "two charts horizantal",
                          title_char = "不同观念级别医生对斯皮仁诺及其推广活动的接受和认可情况（问卷第15、16题）"),
            page15 = list(number_of_dataset = 2,
                          plot_type = c("bar + line","bar + line"),
                          dataset_names =c("smmy_psc_qtr_smmy_nat",
                                           "smmy_psc_qtr_smmy_field"),
                          dataset_1 = list(x1 = "Quarter",
                                           y1 = "adv",
                                           name1 = "Number of Perception Progression",
                                           x2 = "Quarter",
                                           y2 = "adv_ratio",
                                           name2 = "Percentage of Perception Progression",
                                           x_axis = "Quarter",
                                           y1_axis = "Number of Physicans with Perception Progression",
                                           y2_axis = "Percentage",
                                           title_plot = "Tracking of Perception Progression in Overall Physician"),
                          dataset_2 = list(x1 = "Quarter",
                                           y1 = "adv",
                                           name1 = "Number of Perception Progression",
                                           x2 = "Quarter",
                                           y2 = "adv_ratio",
                                           name2 = "Percentage of Perception Progression",
                                           x_axis = "Quarter",
                                           y1_axis = "Number of Physicans with Perception Progression",
                                           y2_axis = "Percentage",
                                           title_plot = paste("Perception progression in", input$field, input$item, sep = " ")),
                          layout = "two charts horizantal",
                          title_char = "每季度进阶医生的总体及在某一特定维度中的变化情况"),
            page16 = list(number_of_dataset = 3,
                          plot_type = c("stacked bar","stacked bar","stacked bar"),
                          dataset_names = c("tmp_smmy_psc_qtr_smmy_region",
                                            "tmp_smmy_psc_qtr_smmy_department",
                                            "tmp_smmy_psc_qtr_smmy_tier"),
                          dataset_1 = list(x = "region",
                                           y = 'ratio',
                                           color = 'item',
                                           x_axis = "Region",
                                           y_axis = "Percentage",
                                           title_plot = paste("Distribution of Physicians Scores by Region in ",
                                                              input$year, input$quarter, sep = "")),
                          dataset_2 = list(x = "department",
                                           y = "ratio",
                                           color = "item",
                                           x_axis = 'Department',
                                           y_axis = "Percentage",
                                           title_plot = paste("Distribution of Physicians Scores by Department in ",
                                                              input$year, input$quarter, sep = "")),
                          dataset_3 = list(x = "doctor.tier",
                                           y = "ratio",
                                           color = "item",
                                           x_axis = "Doctor Level",
                                           y_axis = "Percentage",
                                           title_plot = paste("Distribution of Physicians Scores by Doctor Level in ",
                                                              input$year, input$quarter, sep = "")),
                          layout = "four charts",
                          title_char = "各季度观念进阶医生的分布情况"),
            page17 = list(number_of_dataset = 2,
                          plot_type = c("horizantal bar","horizantal bar"),
                          dataset_names = c("tmp_eda_dat_15_q_adv",
                                            "tmp_eda_dat_16_q_adv"),
                          dataset_1 = list(x = "doc_cnt_pct",
                                           y = "answers",
                                           color = "flag",
                                           x_axis = "Percentage",
                                           y_axis = "Attitude",
                                           title_plot = paste("Sporanox Advantages Accepted by Physicians with Progression ",
                                                              input$year, input$quarter, sep = "")),
                          dataset_2 = list(x = "doc_cnt_pct",
                                           y = "answers",
                                           color = "flag",
                                           x_axis = "Percentage",
                                           y_axis = "Promotional Activities",
                                           title_plot = paste("Sporanox Promotional Activities Accepted by Physicians with Progression ",
                                                              input$year, input$quarter, sep = "")),
                          layout = "two charts horizantal",
                          title_char = "观念进阶医生对斯皮仁诺及其推广活动的接受和认可情况 （问卷第15、16题）"),
            page19 = list(number_of_dataset =2,
                          plot_type = c("multiple bar","multiple bar"),
                          dataset_names = c("tmp_eda_dat_tgt_with_meeting_all",
                                            "tmp_eda_dat_tgt_with_call_all"),
                          dataset_1 = list(x = "imeeting.type",
                                           y = "avg_meeting_cnt",
                                           color = "hcp.major",
                                           x_axis = "Meeting Type",
                                           y_axis = "Average Meeting Counts",
                                           title_plot = paste("Average Meeting Counts for Physicians with Different Scores in ",
                                                              input$year, input$quarter, sep = "")),
                          dataset_2 = list(x = "region",
                                           y = "avg_call_cnt",
                                           color = "hcp.major",
                                           x_axis = "Region",
                                           y_axis = "Average Call counts",
                                           title_plot = paste("Average Call Number for Physicians with Different Scores in ",
                                                              input$year, input$quarter, sep = "")),
                          layout = "two charts vertical",
                          title_char = "不同观念级别医生参与推广活动情况"),
            page20 = list(number_of_dataset = 2,
                          plot_type = c("line","line"),
                          dataset_names = c("tmp1_eda_dat_tgt_with_meeting_all",
                                            "tmp1_eda_dat_tgt_with_call_all"),
                          dataset_1 = list(x = "Quarter",
                                                             y = "avg_meeting_cnt",
                                                             linetype = "hcp.major",
                                                             color = "hcp.major",
                                                             x_axis = "Quarter",
                                                             y_axis = "Average Meeting Counts",
                                                             title_plot = paste("Tracking of Average Meeting Count for Physicians with Different Scores")),
                          dataset_2 = list(x = "Quarter",
                                                             y = "avg_call_cnt",
                                                             linetype ="hcp.major",
                                                             color = "hcp.major",
                                                             x_axis = "Quarter",
                                                             y_axis ="Average Call Counts",
                                                             title_plot = paste("Tracking of Average Call Count for Physicians with Different Scores")),
                          layout = "two charts vertical",
                          title_char = "每季度不同观念级别医生参与的推广活动情况"
                          ),
                          page21 = list(number_of_dataset = 2,
                                        plot_type = c("multiple bar","multiple bar"),
                                        dataset_names = c("tmp_eda_dat_tgt_with_meeting_adv_all",
                                                          "tmp_eda_dat_tgt_with_call_adv_all"),
                                        dataset_1 = list(x = "imeeting.type",
                                                         y = "avg_meeting_cnt",
                                                         color ="adv_flag",
                                                         x_axis = "Meeting type",
                                                         y_axis = "Average Meeting Counts",
                                                         title_plot = paste("Average Meeting Counts for Physicians with Progression VS. Overall in ",
                                                                            input$year, input$quarter, sep = "")),
                                        dataset_2 = list(x = "region",
                                                         y = "avg_call_cnt",
                                                         color = "adv_flag",
                                                         x_axis ="Region",
                                                         y_axis = "Average Call Counts",
                                                         title_plot = paste("Average Call Number for Physicians with Progression VS. Overall in ",
                                                                            input$year, input$quarter, sep = "")),
                                        layout = "two charts vertical",
                                        title_char = "观念进阶医生参与推广活动情况"),
                          page22 = list(number_of_dataset = 2,
                                        plot_type = c("line","line"),
                                        dataset_names = c("tmp1_eda_dat_tgt_with_meeting_adv_all",
                                                          "tmp1_eda_dat_tgt_with_call_adv_all"),
                                        dataset_1 = list(x = "Quarter",
                                                         y = "avg_meeting_cnt",
                                                         linetype = "adv_flag",
                                                         color ="adv_flag",
                                                         x_axis = "Quarter",
                                                         y_axis = "Average Meeting Counts",
                                                         title_plot = paste("Tracking of Average Meeting Count for Physicians with Progression VS. Overall")),
                                        dataset_2 = list(x = "Quarter",
                                                         y = "avg_call_cnt",
                                                         linetype = "adv_flag",
                                                         color = "adv_flag",
                                                         x_axis = "Quarter",
                                                         y_axis = "Average Call Counts",
                                                         title_plot = paste("Tracking of Average Call Count for Physicians with Progression VS. Overall")),
                                        layout = "two charts vertical",
                                        title_char = "每季度观念进阶医生参与推广活动情况")
            )




